{
 "title": "My Dashboard",
 "time": { "from": "2025-03-18T12:35:53.392Z", "to": "2025-03-18T14:10:12.784Z" },
 "panels": [
  {
   "title": "Disk free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}/1024/1024/1024",
     "legendFormat": "Disk free"
    }
   ]
  },
  {
   "title": "Mem Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"}/1024/1024",
     "legendFormat": "Memory free"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100-(\n    irate(\n        node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[5m]\n    )*100\n)",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{instance=\"localhost:9100\"}",
     "legendFormat": "CPULA1"
    },
    {
     "expr": "node_load5{instance=\"localhost:9100\"}",
     "legendFormat": "CPULA5"
    },
    {
     "expr": "node_load15{instance=\"localhost:9100\"}",
     "legendFormat": "CPULA15"
    }
   ]
  }
 ]
}